/* Pontos Alibr — carteira interna compartilhada pelo ChatShop e Blog Alibr. */
(function(){
'use strict';
if(window.__ALIBR_POINTS__) return;
window.__ALIBR_POINTS__=true;
const PROFILE_POINTS=20,BLOG_POST_POINTS=10,REFERRAL_POINTS=30;
const $=(s,r)=>(r||document).querySelector(s);
const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let loadedUid='';
function currentUser(){try{return auth&&auth.currentUser&&!auth.currentUser.isAnonymous?auth.currentUser:null}catch(e){return null}}
function database(){try{return db||null}catch(e){return null}}
function label(type){return ({profile_completed:'Perfil completo',blog_post_approved:'Publicação aprovada',referral_signup:'Indicação cadastrada',admin_adjustment:'Ajuste do administrador'})[type]||'Movimentação'}
function dateText(value){try{return(value&&value.toDate?value.toDate():new Date(value)).toLocaleDateString('pt-BR')}catch(e){return''}}
function installStyle(){if($('#alibrPointsStyle'))return;const s=document.createElement('style');s.id='alibrPointsStyle';s.textContent='.alibr-points-box{grid-column:1/-1;border:1px solid #fde68a;background:linear-gradient(135deg,#fffbeb,#fff7d6);border-radius:14px;padding:14px;margin-top:2px}.alibr-points-top{display:flex;justify-content:space-between;align-items:center;gap:12px}.alibr-points-name{font-weight:900;color:#92400e}.alibr-points-balance{font-size:24px;font-weight:950;color:#b45309;white-space:nowrap}.alibr-points-help{font-size:12px;color:#78350f;margin:5px 0 0}.alibr-points-history{display:none;margin-top:10px;border-top:1px solid #fde68a;padding-top:7px}.alibr-points-history.open{display:block}.alibr-points-row{display:flex;justify-content:space-between;gap:10px;padding:6px 0;font-size:12px;border-bottom:1px solid rgba(245,158,11,.18)}.alibr-points-toggle{border:0;background:transparent;color:#92400e;text-decoration:underline;font-weight:800;padding:7px 0 0;cursor:pointer}';document.head.appendChild(s)}
function installBox(){const grid=$('.alibr-profile-grid');if(!grid||$('#alibrPointsBox'))return false;const box=document.createElement('section');box.id='alibrPointsBox';box.className='alibr-points-box';box.innerHTML='<div class="alibr-points-top"><div><div class="alibr-points-name">⭐ Pontos Alibr</div><p class="alibr-points-help">Ganhe por perfil completo, postagem aprovada e indicação confirmada.</p></div><div id="alibrPointsBalance" class="alibr-points-balance">0</div></div><button id="alibrPointsToggle" class="alibr-points-toggle" type="button">Ver extrato</button><div id="alibrPointsHistory" class="alibr-points-history"></div>';grid.appendChild(box);$('#alibrPointsToggle').onclick=()=>$('#alibrPointsHistory').classList.toggle('open');return true}
async function loadWallet(force){const user=currentUser(),d=database();if(!user||!d)return;installBox();if(!$('#alibrPointsBalance'))return;if(!force&&loadedUid===user.uid)return;loadedUid=user.uid;$('#alibrPointsBalance').textContent='…';try{const snap=await d.collection('pointTransactions').where('beneficiaryUid','==',user.uid).limit(200).get();const rows=snap.docs.map(x=>({id:x.id,...x.data()})).filter(x=>x.status==='confirmed').sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));const balance=rows.reduce((sum,x)=>sum+(Number(x.points)||0),0);$('#alibrPointsBalance').textContent=String(balance);$('#alibrPointsHistory').innerHTML=rows.length?rows.map(x=>'<div class="alibr-points-row"><span>'+esc(label(x.type))+(x.createdAt?' · '+esc(dateText(x.createdAt)):'')+'</span><b>'+(x.points>0?'+':'')+esc(x.points)+'</b></div>').join(''):'<div class="alibr-points-row"><span>Você ainda não possui movimentações.</span></div>'}catch(e){console.warn('Pontos Alibr indisponíveis',e);$('#alibrPointsBalance').textContent='0'}}
async function rewardProfile(){const user=currentUser(),d=database();if(!user||!d)return;try{const p=await d.collection('profiles').doc(user.uid).get(),data=p.exists?p.data()||{}:{};if(String(data.name||'').trim().length<2||String(data.whatsapp||'').replace(/\D/g,'').length<10)return;await d.collection('pointTransactions').doc('profile_'+user.uid).set({beneficiaryUid:user.uid,actorUid:user.uid,type:'profile_completed',sourceId:user.uid,points:PROFILE_POINTS,status:'confirmed',createdAt:firebase.firestore.FieldValue.serverTimestamp()});await loadWallet(true)}catch(e){console.warn('Bônus de perfil não registrado',e)}}
async function rewardReferral(){const user=currentUser(),d=database();if(!user||!d)return;try{const mine=await d.collection('users').doc(user.uid).get(),data=mine.exists?mine.data()||{}:{};const code=String(data.referredBy||'').trim();if(!code)return;const referrer=await d.collection('users').where('affiliateCode','==',code).limit(1).get();if(referrer.empty)return;const beneficiaryUid=referrer.docs[0].id;if(beneficiaryUid===user.uid)return;await d.collection('pointTransactions').doc('referral_'+user.uid).set({beneficiaryUid,actorUid:user.uid,type:'referral_signup',sourceId:user.uid,points:REFERRAL_POINTS,status:'confirmed',createdAt:firebase.firestore.FieldValue.serverTimestamp()})}catch(e){console.warn('Bônus de indicação não registrado',e)}}
async function rewardApprovedPost(postId,authorUid){const user=currentUser(),d=database();if(!user||!d||!postId||!authorUid)return;await d.collection('pointTransactions').doc('blog_'+postId).set({beneficiaryUid:authorUid,actorUid:user.uid,type:'blog_post_approved',sourceId:postId,points:BLOG_POST_POINTS,status:'confirmed',createdAt:firebase.firestore.FieldValue.serverTimestamp()})}
window.AlibrPoints={load:()=>loadWallet(true),rewardApprovedPost};
window.addEventListener('alibr-profile-updated',rewardProfile);
document.addEventListener('click',e=>{if(e.target.closest('#alibrProfileBtn'))setTimeout(()=>loadWallet(true),120)});
function boot(){installStyle();let n=0;const timer=setInterval(()=>{installBox();if(++n>100)clearInterval(timer)},200);try{auth.onAuthStateChanged(u=>{loadedUid='';if(u&&!u.isAnonymous)setTimeout(()=>{rewardReferral();loadWallet(true)},300)})}catch(e){}}
boot();
})();
