/* ChatShop - cupons e links da Loja Virtual */
(function(){
'use strict';
const $=(s,r)=> (r||document).querySelector(s);
const $$=(s,r)=> Array.from((r||document).querySelectorAll(s));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function code(v){return String(v||'').toUpperCase().replace(/[^A-Z0-9_-]/g,'').slice(0,30)}
function number(v){let s=String(v||'').replace(/[^0-9,.-]/g,'');if(s.includes(','))s=s.replace(/\./g,'').replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0}
function money(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function currentSlug(){return String($('#slug')?.value||'sua-loja').trim().toLowerCase().replace(/[^a-z0-9-]/g,'')||'sua-loja'}
function makeLink(base,cupom,ref){try{const u=new URL(base||`https://${currentSlug()}.alibr.com.br`,location.origin);if(cupom)u.searchParams.set('cupom',code(cupom));if(ref)u.searchParams.set('ref',String(ref).trim());return u.toString()}catch(e){return String(base||'')}}

/* ================= EDITOR ================= */
function couponRow(c={}){
 const el=document.createElement('div');el.className='cs-coupon-row';el.style.cssText='border:1px solid #ddd6fe;background:#faf5ff;border-radius:12px;padding:10px;margin:9px 0';
 el.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center"><b>🎟️ Cupom</b><button type="button" class="cs-coupon-remove" style="border:0;background:#fee2e2;color:#b91c1c;border-radius:8px;padding:6px 9px">Excluir</button></div>
 <div class="grid2"><div class="field"><label>Código</label><input data-c="code" placeholder="BEMVINDO10"></div><div class="field"><label>Tipo</label><select data-c="type"><option value="percent">Percentual (%)</option><option value="fixed">Valor (R$)</option></select></div></div>
 <div class="grid2"><div class="field"><label>Valor do desconto</label><input data-c="value" inputmode="decimal" placeholder="Ex: 10"></div><div class="field"><label>Compra mínima</label><input data-c="min" inputmode="decimal" placeholder="Ex: 100"></div></div>
 <div class="grid2"><div class="field"><label>Validade (opcional)</label><input type="date" data-c="expires"></div><div class="field"><label>Status</label><select data-c="active"><option value="1">Ativo</option><option value="0">Pausado</option></select></div></div>
 <div class="field"><label>Link pronto do cupom</label><div style="display:flex;gap:6px"><input class="cs-coupon-link" readonly><button type="button" class="btn cs-coupon-copy">Copiar</button></div><small>Este cupom pode ser colocado no link da loja ou de qualquer produto do ChatShop.</small></div>`;
 const set=(k,v)=>{const x=el.querySelector(`[data-c="${k}"]`);if(x)x.value=v??''};set('code',c.code||'');set('type',c.type||'percent');set('value',c.value||'');set('min',c.minSubtotal||'');set('expires',c.expiresAt||'');set('active',c.active===false?'0':'1');
 function refresh(){const i=el.querySelector('[data-c="code"]');i.value=code(i.value);el.querySelector('.cs-coupon-link').value=makeLink('',i.value,'');refreshCouponSelect();try{window.debounce?.()}catch(e){}}
 el.querySelectorAll('input,select').forEach(i=>{i.addEventListener('input',refresh);i.addEventListener('change',refresh)});el.querySelector('.cs-coupon-remove').onclick=()=>{el.remove();refreshCouponSelect()};el.querySelector('.cs-coupon-copy').onclick=async()=>{try{await navigator.clipboard.writeText(el.querySelector('.cs-coupon-link').value);window.toast?.('Link do cupom copiado!')}catch(e){}};setTimeout(refresh,0);return el;
}
function readCoupons(){return $$('.cs-coupon-row').map(el=>({code:code(el.querySelector('[data-c="code"]').value),type:el.querySelector('[data-c="type"]').value==='fixed'?'fixed':'percent',value:number(el.querySelector('[data-c="value"]').value),minSubtotal:number(el.querySelector('[data-c="min"]').value),expiresAt:el.querySelector('[data-c="expires"]').value||'',active:el.querySelector('[data-c="active"]').value!=='0'})).filter(x=>x.code&&x.value>0)}
function fillCoupons(list){const b=$('#csCouponList');if(!b)return;b.innerHTML='';(Array.isArray(list)?list:[]).forEach(c=>b.appendChild(couponRow(c)));refreshCouponSelect()}
function refreshCouponSelect(){const s=$('#affiliateCoupon');if(!s)return;const old=s.value;s.innerHTML='<option value="">Sem cupom</option>'+readCoupons().map(c=>`<option value="${esc(c.code)}">${esc(c.code)}</option>`).join('');if([...s.options].some(o=>o.value===old))s.value=old;updateLinkOutput()}
function updateLinkOutput(){const o=$('#affiliateLinkOutput');if(o)o.value=makeLink($('#affiliateBaseLink')?.value.trim()||'', $('#affiliateCoupon')?.value||'', $('#affiliateRef')?.value.trim()||'')}
function ensureEditor(){
 if($('#csCouponSettings')||!$('#storeType'))return;
 const sec=document.createElement('div');sec.className='section';sec.id='csCouponSettings';sec.innerHTML=`<h2>🎟️ Cupons e links de afiliado</h2><div class="notice">O lojista cria o cupom aqui. No link ele fica como <b>?cupom=CODIGO</b>. Se o link já tiver outro parâmetro, o sistema acrescenta o cupom sem apagar o que já existe.</div><div id="csCouponList"></div><button type="button" class="btn" id="csAddCoupon" style="width:100%;margin:10px 0 14px">+ Criar cupom</button><div style="border:1px solid #bfdbfe;background:#eff6ff;border-radius:12px;padding:11px"><b>🔗 Gerador de link para afiliado</b><div class="field" style="margin-top:8px"><label>Link da loja ou do produto</label><input id="affiliateBaseLink" placeholder="Cole qualquer link de produto do ChatShop"><small>Se deixar vazio, usa o endereço principal desta loja.</small></div><div class="grid2"><div class="field"><label>Código do afiliado</label><input id="affiliateRef" placeholder="Ex: MARIA123"></div><div class="field"><label>Cupom</label><select id="affiliateCoupon"><option value="">Sem cupom</option></select></div></div><div class="field"><label>Link final pronto</label><div style="display:flex;gap:6px"><input id="affiliateLinkOutput" readonly><button type="button" class="btn" id="affiliateCopy">Copiar</button></div><small>Exemplo: ?ref=MARIA123&cupom=BEMVINDO10</small></div></div>`;
 const pub=$$('.section').find(x=>(x.querySelector('h2')?.textContent||'').includes('Publicar'));if(pub)pub.parentNode.insertBefore(sec,pub);else $('.panel')?.appendChild(sec);$('#csAddCoupon').onclick=()=>$('#csCouponList').appendChild(couponRow({type:'percent',active:true}));['affiliateBaseLink','affiliateRef'].forEach(id=>$('#'+id).addEventListener('input',updateLinkOutput));$('#affiliateCoupon').addEventListener('change',updateLinkOutput);$('#affiliateCopy').onclick=async()=>{try{await navigator.clipboard.writeText($('#affiliateLinkOutput').value);window.toast?.('Link de afiliado copiado!')}catch(e){}};$('#slug')?.addEventListener('input',()=>{updateLinkOutput();$$('.cs-coupon-row').forEach(r=>r.querySelector('[data-c="code"]')?.dispatchEvent(new Event('input')))});updateLinkOutput();
}
function wrapEditor(){if(typeof window.collect==='function'&&!window.collect.__coupons){const old=window.collect;const fn=function(){const d=old();d.coupons=readCoupons();return d};fn.__coupons=true;window.collect=fn}if(typeof window.populateForm==='function'&&!window.populateForm.__coupons){const old=window.populateForm;const fn=async function(d){const r=await old(d);ensureEditor();fillCoupons(d?.coupons||[]);return r};fn.__coupons=true;window.populateForm=fn}if(typeof window.clearForm==='function'&&!window.clearForm.__coupons){const old=window.clearForm;const fn=function(){const r=old();setTimeout(()=>fillCoupons([]),0);return r};fn.__coupons=true;window.clearForm=fn}}
async function bootEditor(){for(let i=0;i<80;i++){if($('#storeType')){ensureEditor();wrapEditor();return}await sleep(100)}}

/* ================= LOJA PUBLICADA ================= */
function isValid(c){if(!c||c.active===false||!c.code||Number(c.value)<=0)return false;if(c.expiresAt){const d=new Date(c.expiresAt+'T23:59:59');if(Number.isFinite(d.getTime())&&Date.now()>d.getTime())return false}return true}
function discount(sub,c){if(!isValid(c)||sub<Number(c.minSubtotal||0))return 0;return c.type==='fixed'?Math.min(sub,Number(c.value)):Math.min(sub,sub*Math.min(100,Number(c.value))/100)}
function parseDisplayedMoney(t){const m=String(t||'').match(/([0-9][0-9.]*,[0-9]{2}|[0-9]+(?:\.[0-9]{1,2})?)/);return m?number(m[1]):0}
async function bootStore(){
 const host=location.hostname.toLowerCase(),suffix='.alibr.com.br';if(!host.endsWith(suffix)||host==='www.alibr.com.br')return;const storeSlug=host.slice(0,-suffix.length);if(!storeSlug||storeSlug.includes('.'))return;
 let data;try{const db=window.firebase?.firestore?.();if(!db)return;const snap=await db.collection('chatshops').doc(storeSlug).get();if(!snap.exists)return;data=snap.data()}catch(e){return}if(data.storeType!=='virtual'||!Array.isArray(data.coupons)||!data.coupons.length)return;
 const all=data.coupons,products=Array.isArray(data.products)?data.products:[],params=new URLSearchParams(location.search),ref=String(params.get('ref')||'').trim();let applied=all.find(x=>code(x.code)===code(params.get('cupom'))&&isValid(x))||null,cart=[],active=-1,selectedColor='';
 function subtotal(){return cart.reduce((a,x)=>a+x.price*x.qty,0)}
 function addShadow(i,c,q){const p=products[i];if(!p)return;const key=i+'|'+String(c||''),hit=cart.find(x=>x.key===key);if(hit)hit.qty+=q;else cart.push({key,index:i,color:c||'',qty:q,price:number(p.price)})}
 function freightValue(){const f=$('#csvFreight');if(f&&!/gr[aá]tis|combinar|calcule/i.test(f.textContent||''))return parseDisplayedMoney(f.textContent);const selected=$('#sfQuoteOptions input:checked')?.closest('label');return selected?parseDisplayedMoney(selected.textContent):0}
 function renderCouponBox(){const body=$('#csvCartBody')||$('#vsCartBody');if(!body||!cart.length)return;if(!$('#csCouponCart')){const box=document.createElement('div');box.id='csCouponCart';box.style.cssText='border:1px solid #ddd6fe;background:#faf5ff;border-radius:12px;padding:11px;margin:12px 0';box.innerHTML=`<b>🎟️ Cupom de desconto</b><div style="display:flex;gap:7px;margin-top:8px"><input id="csCouponInput" placeholder="Digite o cupom" maxlength="30" style="flex:1;min-width:0;border:1px solid #c4b5fd;border-radius:9px;padding:10px;text-transform:uppercase"><button id="csApplyCoupon" type="button" style="border:0;background:#6d28d9;color:#fff;border-radius:9px;padding:0 13px;font-weight:900">Aplicar</button></div><div id="csCouponStatus" style="font-size:12px;margin-top:7px"></div><div style="display:flex;justify-content:space-between;margin-top:8px"><span>Desconto</span><b id="csCouponDiscount">${money(0)}</b></div>`;const anchor=body.querySelector('.csv-summary')||body.querySelector('.vs-total')||body.querySelector('#csvCheckout')||body.querySelector('#vsCheckout');anchor?anchor.insertAdjacentElement('beforebegin',box):body.appendChild(box);$('#csCouponInput').value=applied?.code||'';$('#csApplyCoupon').onclick=()=>{const entered=code($('#csCouponInput').value);applied=all.find(x=>code(x.code)===entered&&isValid(x))||null;updateCouponUI()}}updateCouponUI()}
 function updateCouponUI(){const sub=subtotal(),d=discount(sub,applied),status=$('#csCouponStatus');if(status){if(!applied){status.textContent='Cupom inválido, pausado ou vencido.';status.style.color='#b91c1c'}else if(sub<Number(applied.minSubtotal||0)){status.textContent='Compra mínima de '+money(applied.minSubtotal)+' para usar '+applied.code+'.';status.style.color='#92400e'}else{status.textContent='✅ Cupom '+applied.code+' aplicado.';status.style.color='#166534'}}if($('#csCouponDiscount'))$('#csCouponDiscount').textContent=d?'-'+money(d):money(0);if(d>0){const total=Math.max(0,sub-d)+freightValue();if($('#csvTotal'))$('#csvTotal').textContent=money(total);const vt=$('.vs-total span:last-child');if(vt)vt.textContent=money(total);if($('#sfCartTotal'))$('#sfCartTotal').textContent=money(total)}}
 document.addEventListener('click',e=>{const o=e.target.closest('#csvGrid [data-product],#vsGrid [data-product]');if(o){active=Number(o.dataset.product);selectedColor='';return}const c=e.target.closest('.csv-color,.vs-color');if(c){selectedColor=c.dataset.color||'';return}if(e.target.closest('#csvAdd,#vsAdd')){const q=Math.max(1,Number($('#csvQty')?.textContent||$('#vsQty')?.textContent||1));if(active>=0)addShadow(active,selectedColor,q);setTimeout(renderCouponBox,30);return}const r=e.target.closest('[data-remove]');if(r&&($('#csvCartBody')?.contains(r)||$('#vsCartBody')?.contains(r))){const i=Number(r.dataset.remove);if(Number.isInteger(i))cart.splice(i,1);setTimeout(renderCouponBox,30);return}if(e.target.closest('#csvBag,#vsBag'))setTimeout(renderCouponBox,40)},true);
 // Quando há desconto válido, finaliza com o valor descontado e mantém os dados de entrega visíveis na sacola.
 window.addEventListener('click',e=>{const btn=e.target.closest('#csvCheckout,#vsCheckout');if(!btn||!applied)return;const sub=subtotal(),disc=discount(sub,applied);if(!(disc>0))return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const phone=String(data.whatsapp||'').replace(/\D/g,'');if(!phone)return;const frete=freightValue(),total=Math.max(0,sub-disc)+frete,lines=['Olá! Quero fazer este pedido:',''];cart.forEach(x=>{const p=products[x.index]||{};lines.push('• '+(p.name||'Produto')+(x.color?' | Cor: '+x.color:'')+' | Qtd: '+x.qty+' | '+money(x.price*x.qty))});lines.push('','Subtotal: '+money(sub),'Cupom: '+applied.code+' (-'+money(disc)+')');if(frete>0)lines.push('Frete: '+money(frete));const address=($('#sfAddress')?.value||$('#csvAddress')?.value||'').trim();if(address)lines.push('Endereço: '+address);lines.push('Total: '+money(total));if(ref)lines.push('Afiliado: '+ref);window.open('https://wa.me/'+phone+'?text='+encodeURIComponent(lines.join('\n')),'_blank','noopener')},true);
 if(applied){const head=$('.csv-head')||$('.vs-head');if(head){const b=document.createElement('div');b.style.cssText='background:#ecfdf5;color:#166534;text-align:center;padding:8px;font-size:12px;font-weight:900';b.textContent='🎟️ Cupom '+applied.code+' carregado pelo link';head.insertAdjacentElement('afterend',b)}}
 const root=$('#storefrontScreen')||document.body;new MutationObserver(()=>{if($('#csvCartBody')||$('#vsCartBody'))requestAnimationFrame(renderCouponBox)}).observe(root,{childList:true,subtree:true});
}
bootEditor();bootStore();
})();
