/* ShopAds Wallet — Etapa 5: carteira de teste do divulgador. */
(function(){
'use strict';
const $=(s,r)=>(r||document).querySelector(s);
function dbRef(){try{return typeof db!=='undefined'&&db?db:null}catch(e){return null}}
function uid(){try{return typeof myUid!=='undefined'&&myUid?myUid:(typeof currentUser!=='undefined'&&currentUser?.uid?currentUser.uid:'')}catch(e){return''}}
function brl(v){return 'R$ '+Number(v||0).toFixed(2).replace('.',',')}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function admin(){try{return typeof isAdmin!=='undefined'&&isAdmin===true}catch(e){return false}}
async function getClicks(){const d=dbRef();if(!d||!uid())return[];try{const s=await d.collection('shopadsClicks').where('promoterUid','==',uid()).get();return s.docs.map(x=>({id:x.id,...x.data()}))}catch(e){console.warn('ShopAds carteira:',e);return[]}}
async function getCampaigns(){const d=dbRef();if(!d)return{};try{const s=await d.collection('shopadsCampaigns').get(),m={};s.docs.forEach(x=>m[x.id]={id:x.id,...x.data()});return m}catch(e){return{}}}
function styles(){if($('#shopAdsWalletStyles'))return;const s=document.createElement('style');s.id='shopAdsWalletStyles';s.textContent=`#shopAdsWallet{position:fixed;inset:0;z-index:10080;background:#f7f5ff;overflow:auto;display:none;font-family:Arial,sans-serif;color:#1f2937}#shopAdsWallet.open{display:block}.saw-top{background:linear-gradient(135deg,#166534,#16a34a);color:#fff;padding:18px}.saw-head{max-width:760px;margin:auto;display:flex;align-items:center;justify-content:space-between}.saw-brand{font-size:24px;font-weight:900}.saw-close{border:0;background:#ffffff25;color:#fff;width:40px;height:40px;border-radius:50%;font-size:20px}.saw-body{max-width:760px;margin:auto;padding:16px}.saw-card{background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:16px;margin-bottom:12px;box-shadow:0 8px 22px #0000000d}.saw-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.saw-metric{padding:14px;border-radius:12px;background:#f9fafb;text-align:center;font-size:12px}.saw-metric b{display:block;font-size:22px;margin-top:5px}.saw-pending b{color:#b45309}.saw-approved b{color:#15803d}.saw-total b{color:#5b21b6}.saw-row{padding:12px 0;border-top:1px solid #eee;font-size:13px}.saw-row:first-child{border-top:0}.saw-pill{display:inline-block;font-size:10px;font-weight:900;border-radius:999px;padding:4px 7px;background:#fef3c7;color:#92400e}.saw-pill.ok{background:#dcfce7;color:#166534}.saw-note{font-size:12px;color:#6b7280;line-height:1.45}.saw-btn{border:0;border-radius:10px;padding:12px 14px;font-weight:900;background:#16a34a;color:#fff;width:100%;cursor:pointer}@media(max-width:560px){.saw-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
async function openWallet(){styles();let el=$('#shopAdsWallet');if(!el){el=document.createElement('div');el.id='shopAdsWallet';document.body.appendChild(el)}el.classList.add('open');el.innerHTML=`<div class="saw-top"><div class="saw-head"><div class="saw-brand">💰 Minha carteira ShopAds</div><button class="saw-close">×</button></div></div><main class="saw-body"><section class="saw-card" id="sawContent">Carregando carteira...</section></main>`;$('.saw-close',el).onclick=()=>el.classList.remove('open');const box=$('#sawContent',el);if(!uid()){box.innerHTML='<p>Entre na sua conta para ver a carteira.</p>';return}const [clicks,camps]=await Promise.all([getClicks(),getCampaigns()]);const valid=clicks.filter(x=>x.valid!==false&&!x.duplicate);let pending=0,approved=0;const rows=[];valid.forEach(x=>{const c=camps[x.campaignId]||{},value=Number(x.reward!=null?x.reward:c.reward||0),status=x.paymentStatus||x.balanceStatus||'pendente';if(status==='aprovado')approved+=value;else pending+=value;rows.push({x,c,value,status})});const total=pending+approved;box.innerHTML=`<h2 style="margin-top:0">Saldo de teste</h2><div class="saw-grid"><div class="saw-metric saw-pending">Pendente<b>${brl(pending)}</b></div><div class="saw-metric saw-approved">Aprovado<b>${brl(approved)}</b></div><div class="saw-metric saw-total">Acumulado<b>${brl(total)}</b></div></div><p class="saw-note">Valores calculados somente com cliques válidos. Esta carteira está em modo de teste: não existe saque ou pagamento real liberado.</p></section><section class="saw-card"><h2 style="margin-top:0">Histórico</h2>${rows.length?rows.slice().reverse().slice(0,100).map(r=>`<div class="saw-row"><b>${esc(r.c.title||r.x.campaignId||'Campanha')}</b><br>${brl(r.value)} · <span class="saw-pill ${r.status==='aprovado'?'ok':''}">${r.status==='aprovado'?'APROVADO':'PENDENTE'}</span><br><small>${esc(r.x.createdAt||r.x.timestamp||'')}</small></div>`).join(''):'<p>Nenhum resultado válido registrado ainda.</p>'}</section><section class="saw-card"><button class="saw-btn" disabled style="opacity:.55">Solicitar saque — EM BREVE</button><p class="saw-note">O saque só será ativado depois da implantação de pagamentos, validação antifraude e regras de aprovação.</p></section>`}
function installButton(){if($('#shopAdsWalletBtn'))return;const tryInstall=()=>{if($('#shopAdsWalletBtn'))return true;const shop=$('#shopAdsBtn,[data-open-shopads]');if(!shop||!shop.parentElement)return false;const b=document.createElement('button');b.id='shopAdsWalletBtn';b.type='button';b.className=shop.className||'btn';b.textContent='💰 Carteira ShopAds';b.onclick=openWallet;shop.parentElement.insertBefore(b,shop.nextSibling);return true};if(tryInstall())return;let n=0,t=setInterval(()=>{n++;if(tryInstall()||n>100)clearInterval(t)},250)}
window.openShopAdsWallet=openWallet;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',installButton);else installButton();
})();