/* ShopAds — pagamento de campanhas pelo Mercado Pago. */
(function(){
'use strict';
if(window.__SHOPADS_PAYMENT__)return;window.__SHOPADS_PAYMENT__=true;
const $=(s,r)=>(r||document).querySelector(s);
function uid(){try{return typeof myUid!=='undefined'&&myUid?myUid:(typeof currentUser!=='undefined'&&currentUser?.uid?currentUser.uid:firebase?.auth?.().currentUser?.uid||'')}catch(e){return''}}
function email(){try{return typeof currentUser!=='undefined'&&currentUser?.email?currentUser.email:(firebase?.auth?.().currentUser?.email||'')}catch(e){return''}}
function dbRef(){try{return typeof db!=='undefined'&&db?db:null}catch(e){return null}}
async function campaign(id){const d=dbRef();if(!d||!id)return null;try{const s=await d.collection('shopadsCampaigns').doc(id).get();return s.exists?{id:s.id,...s.data()}:null}catch(e){return null}}
async function api(action,body){const r=await fetch('/api/content.js?action='+encodeURIComponent(action),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body||{})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||j.error||'Não foi possível processar o pagamento.');return j}
async function startPayment(id,btn){const c=await campaign(id);if(!c)return alert('Campanha não encontrada.');if(c.ownerUid!==uid())return alert('Esta campanha não pertence à sua conta.');if(Number(c.budget||0)<=0)return alert('Informe um orçamento maior que zero antes de pagar.');if(c.paymentStatus==='approved')return alert('Esta campanha já está paga.');const old=btn?.textContent;if(btn){btn.disabled=true;btn.textContent='Abrindo Mercado Pago...'}try{const j=await api('shopads-pagamento',{campaignId:id,uid:uid(),email:email()});if(!j.checkoutUrl)throw new Error('O Mercado Pago não retornou o link de pagamento.');location.href=j.checkoutUrl}catch(e){alert(e.message)}finally{if(btn){btn.disabled=false;btn.textContent=old||'💳 Pagar campanha'}}}
async function decorate(){document.querySelectorAll('#shopAdsOverlay [data-review]').forEach(async b=>{if(b.dataset.paymentChecked==='1')return;b.dataset.paymentChecked='1';const id=b.dataset.review,c=await campaign(id);if(!c)return;if(c.paymentStatus==='approved'){b.textContent='Enviar para aprovação';return}b.removeAttribute('data-review');b.dataset.shopadsPay=id;b.textContent=c.paymentStatus==='pending'?'💳 Continuar pagamento':'💳 Pagar campanha';b.style.background='#2563eb';b.style.color='#fff'});document.querySelectorAll('#shopAdsAdminPanel [data-ca]').forEach(async b=>{if(b.dataset.payGuard==='1')return;b.dataset.payGuard='1';const c=await campaign(b.dataset.ca);if(c&&c.paymentStatus!=='approved'){b.disabled=true;b.textContent='Pagamento pendente';b.title='A campanha só pode ser aprovada depois que o Mercado Pago confirmar o pagamento.'}})}
document.addEventListener('click',e=>{const b=e.target.closest('[data-shopads-pay]');if(!b)return;e.preventDefault();e.stopPropagation();startPayment(b.dataset.shopadsPay,b)},true);
async function handleReturn(){const q=new URLSearchParams(location.search);if(q.get('shopads_payment')!=='return')return;const id=q.get('campaign')||'',paymentId=q.get('payment_id')||q.get('collection_id')||'';if(!id)return;let tries=0;const run=async()=>{if(!uid()&&tries++<20)return setTimeout(run,300);try{if(!paymentId)throw new Error('Pagamento recebido, mas ainda sem confirmação do Mercado Pago. Abra suas campanhas em alguns instantes.');const j=await api('shopads-status',{campaignId:id,uid:uid(),paymentId});if(j.approved)alert('✅ Pagamento confirmado! Sua campanha foi enviada para aprovação do administrador.');else alert('Pagamento ainda não foi aprovado pelo Mercado Pago. Status: '+String(j.status||'pendente'));const u=new URL(location.href);['shopads_payment','campaign','payment_id','collection_id','collection_status','payment_type','merchant_order_id','preference_id','site_id','processing_mode','merchant_account_id','status','external_reference'].forEach(k=>u.searchParams.delete(k));history.replaceState({},'',u.pathname+(u.search?'?'+u.searchParams.toString():'')+u.hash);setTimeout(()=>{window.openShopAds?.('advertiser')},300)}catch(e){alert(e.message)}};run()}
const obs=new MutationObserver(decorate);if(document.documentElement)obs.observe(document.documentElement,{childList:true,subtree:true});setInterval(decorate,1200);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{decorate();handleReturn()},{once:true});else{decorate();handleReturn()}
})();
