/* ShopAds Admin — Etapa 6: moderação, visão geral e aprovação de saldo de teste. */
(function(){
'use strict';
const ADMIN_EMAILS=['jeanaguiar636@gmail.com','afiliado9591@gmail.com'];
const $=(s,r)=>(r||document).querySelector(s);
function dbRef(){try{return typeof db!=='undefined'&&db?db:null}catch(e){return null}}
function currentEmail(){try{return String((typeof currentUser!=='undefined'&&currentUser&&currentUser.email)||'').trim().toLowerCase()}catch(e){return''}}
function adminOk(){try{if(typeof isAdmin!=='undefined'&&isAdmin===true)return true}catch(e){}return ADMIN_EMAILS.includes(currentEmail())}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function brl(v){return 'R$ '+Number(v||0).toFixed(2).replace('.',',')}
function when(v){if(!v)return '—';try{return new Date(v).toLocaleString('pt-BR')}catch(e){return String(v)}}
function ensureStyles(){if($('#shopAdsAdminStyles'))return;const s=document.createElement('style');s.id='shopAdsAdminStyles';s.textContent=`
.sa-admin-btn{margin-top:12px;background:#111827!important;color:#fff!important}.sa-admin-panel{position:fixed;inset:0;z-index:10070;background:#f3f4f6;overflow:auto;font-family:Arial,sans-serif;color:#111827}.saa-top{background:#111827;color:#fff;padding:16px}.saa-head{max-width:920px;margin:auto;display:flex;align-items:center;justify-content:space-between;gap:10px}.saa-head h1{font-size:22px;margin:0}.saa-close{border:0;background:#ffffff22;color:#fff;border-radius:999px;width:40px;height:40px;font-size:20px;cursor:pointer}.saa-body{max-width:920px;margin:auto;padding:16px}.saa-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:14px}.saa-metric,.saa-card{background:#fff;border:1px solid #e5e7eb;border-radius:14px;padding:14px;box-shadow:0 5px 18px #1118270d}.saa-metric small{display:block;color:#6b7280;font-weight:700}.saa-metric b{display:block;font-size:24px;margin-top:5px}.saa-card{margin-bottom:14px}.saa-card h2{font-size:17px;margin:0 0 10px}.saa-row{border-top:1px solid #eee;padding:12px 0}.saa-row:first-child{border-top:0}.saa-title{font-weight:900}.saa-meta{font-size:12px;color:#6b7280;line-height:1.5;margin-top:4px;word-break:break-word}.saa-actions{display:flex;flex-wrap:wrap;gap:7px;margin-top:9px}.saa-actions button{border:0;border-radius:9px;padding:9px 11px;font-weight:800;cursor:pointer}.saa-ok{background:#dcfce7;color:#166534}.saa-block{background:#fee2e2;color:#991b1b}.saa-muted{background:#f3f4f6;color:#374151}.saa-badge{display:inline-block;border-radius:999px;padding:4px 7px;font-size:10px;font-weight:900;background:#e5e7eb;color:#374151}.saa-badge.live,.saa-badge.approved{background:#dcfce7;color:#166534}.saa-badge.blocked{background:#fee2e2;color:#991b1b}.saa-badge.pending{background:#fef3c7;color:#92400e}.saa-alert{background:#fff7ed;color:#9a3412;border:1px solid #fed7aa;border-radius:10px;padding:10px;font-size:12px;margin-bottom:12px}.saa-summary{display:flex;gap:10px;flex-wrap:wrap;margin:8px 0 12px}.saa-summary span{background:#f9fafb;border:1px solid #e5e7eb;border-radius:10px;padding:8px 10px;font-size:12px}@media(max-width:700px){.saa-grid{grid-template-columns:repeat(2,1fr)}}`;
document.head.appendChild(s)}
async function getCollection(name){const d=dbRef();if(!d)throw new Error('Firebase indisponível');const snap=await d.collection(name).get();return snap.docs.map(x=>({id:x.id,...x.data()}))}
async function setCampaignStatus(id,status){const d=dbRef();if(!d)throw new Error('Firebase indisponível');await d.collection('shopadsCampaigns').doc(id).set({status,updatedAt:new Date().toISOString(),moderatedAt:new Date().toISOString(),moderatedBy:currentEmail()},{merge:true})}
async function setClickBalanceStatus(id,status){const d=dbRef();if(!d)throw new Error('Firebase indisponível');await d.collection('shopadsClicks').doc(id).set({paymentStatus:status,balanceStatus:status,balanceReviewedAt:new Date().toISOString(),balanceReviewedBy:currentEmail()},{merge:true})}
async function approvePromoterPending(promoterUid,clicks){const pending=clicks.filter(x=>x.promoterUid===promoterUid&&x.valid!==false&&!x.duplicate&&(x.paymentStatus||x.balanceStatus||'pendente')!=='aprovado');for(const x of pending)await setClickBalanceStatus(x.id,'aprovado');return pending.length}
function statusLabel(v){if(v==='teste')return ['PUBLICADA','live'];if(v==='bloqueada')return ['BLOQUEADA','blocked'];return ['RASCUNHO','']}
async function openAdmin(){if(!adminOk())return alert('Área exclusiva do administrador do ShopAds.');ensureStyles();let el=$('#shopAdsAdminPanel');if(!el){el=document.createElement('div');el.id='shopAdsAdminPanel';el.className='sa-admin-panel';document.body.appendChild(el)}el.style.display='block';el.innerHTML=`<div class="saa-top"><div class="saa-head"><h1>🛡️ Admin ShopAds</h1><button class="saa-close" aria-label="Fechar">×</button></div></div><main class="saa-body"><div id="saaContent">Carregando dados...</div></main>`;$('.saa-close',el).onclick=()=>{el.style.display='none'};const box=$('#saaContent',el);try{const [campaigns,clicks,links]=await Promise.all([getCollection('shopadsCampaigns'),getCollection('shopadsClicks'),getCollection('shopadsLinks')]);const valid=clicks.filter(x=>x.valid!==false&&!x.duplicate),duplicates=clicks.filter(x=>x.duplicate===true||x.valid===false),promoters=new Set(links.map(x=>x.promoterUid).filter(Boolean)),advertisers=new Set(campaigns.map(x=>x.ownerUid).filter(Boolean));const estimated=valid.reduce((s,x)=>s+Number(x.reward||0),0),approvedTotal=valid.filter(x=>(x.paymentStatus||x.balanceStatus)==='aprovado').reduce((s,x)=>s+Number(x.reward||0),0),pendingTotal=estimated-approvedTotal;box.innerHTML=`<div class="saa-grid"><div class="saa-metric"><small>Campanhas</small><b>${campaigns.length}</b></div><div class="saa-metric"><small>Cliques válidos</small><b>${valid.length}</b></div><div class="saa-metric"><small>Saldo pendente</small><b>${brl(pendingTotal)}</b></div><div class="saa-metric"><small>Saldo aprovado</small><b>${brl(approvedTotal)}</b></div></div><div class="saa-alert">Modo de teste: aprovar saldo apenas muda o status interno do resultado. Nenhum pagamento ou saque real é executado.</div><section class="saa-card"><h2>Campanhas e moderação</h2><div id="saaCampaigns"></div></section><section class="saa-card"><h2>💰 Aprovação de saldo dos divulgadores</h2><div id="saaBalances"></div></section><section class="saa-card"><h2>Rede ShopAds</h2><div class="saa-meta">Anunciantes: <b>${advertisers.size}</b> · Divulgadores com link: <b>${promoters.size}</b> · Links gerados: <b>${links.length}</b> · Repetidos filtrados: <b>${duplicates.length}</b></div></section><section class="saa-card"><h2>Cliques recentes</h2><div id="saaClicks"></div></section>`;
const cbox=$('#saaCampaigns',box);if(!campaigns.length)cbox.innerHTML='<p>Nenhuma campanha criada.</p>';else cbox.innerHTML=campaigns.sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||''))).map(c=>{const [label,klass]=statusLabel(c.status);return `<div class="saa-row"><div class="saa-title">${esc(c.title||'Campanha sem nome')} <span class="saa-badge ${klass}">${label}</span></div><div class="saa-meta">Anunciante: ${esc(c.ownerEmail||c.ownerUid||'—')}<br>Orçamento teste: ${brl(c.budget)} · Recompensa: ${brl(c.reward)} por ${esc(c.resultType||'resultado')}<br>Destino: ${esc(c.url||'—')}</div><div class="saa-actions">${c.status!=='teste'?`<button class="saa-ok" data-approve="${esc(c.id)}">Aprovar/Publicar</button>`:''}${c.status!=='bloqueada'?`<button class="saa-block" data-block="${esc(c.id)}">Bloquear</button>`:''}<button class="saa-muted" data-draft="${esc(c.id)}">Rascunho</button></div></div>`}).join('');cbox.onclick=async e=>{const a=e.target.closest('[data-approve]'),b=e.target.closest('[data-block]'),r=e.target.closest('[data-draft]');try{if(a)await setCampaignStatus(a.dataset.approve,'teste');if(b)await setCampaignStatus(b.dataset.block,'bloqueada');if(r)await setCampaignStatus(r.dataset.draft,'rascunho');if(a||b||r)openAdmin()}catch(err){alert('Não foi possível alterar a campanha: '+err.message)}};
const grouped={};valid.forEach(x=>{const p=x.promoterUid||'sem-divulgador';if(!grouped[p])grouped[p]={uid:p,email:x.promoterEmail||'',pending:0,approved:0,pendingCount:0,approvedCount:0};const val=Number(x.reward||0),st=x.paymentStatus||x.balanceStatus||'pendente';if(st==='aprovado'){grouped[p].approved+=val;grouped[p].approvedCount++}else{grouped[p].pending+=val;grouped[p].pendingCount++}});const bbox=$('#saaBalances',box),groups=Object.values(grouped).sort((a,b)=>b.pending-a.pending);bbox.innerHTML=groups.length?groups.map(g=>`<div class="saa-row"><div class="saa-title">${esc(g.email||g.uid)} ${g.pendingCount?'<span class="saa-badge pending">PENDENTE</span>':'<span class="saa-badge approved">OK</span>'}</div><div class="saa-summary"><span>Pendente: <b>${brl(g.pending)}</b> (${g.pendingCount})</span><span>Aprovado: <b>${brl(g.approved)}</b> (${g.approvedCount})</span></div>${g.pendingCount?`<div class="saa-actions"><button class="saa-ok" data-approve-promoter="${esc(g.uid)}">Aprovar saldo pendente</button></div>`:''}</div>`).join(''):'<p>Nenhum saldo válido para revisar.</p>';bbox.onclick=async e=>{const b=e.target.closest('[data-approve-promoter]');if(!b)return;if(!confirm('Aprovar todos os resultados pendentes deste divulgador?'))return;b.disabled=true;b.textContent='Aprovando...';try{const n=await approvePromoterPending(b.dataset.approvePromoter,clicks);alert(n+' resultado(s) aprovado(s) no modo de teste.');openAdmin()}catch(err){alert('Não foi possível aprovar o saldo: '+err.message);b.disabled=false;b.textContent='Aprovar saldo pendente'}};
const recent=[...clicks].sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||''))).slice(0,50),xbox=$('#saaClicks',box);xbox.innerHTML=recent.length?recent.map(x=>{const st=x.paymentStatus||x.balanceStatus||'pendente';return `<div class="saa-row"><div class="saa-title">${x.duplicate||x.valid===false?'⚠️ Repetido/filtrado':'✅ Clique válido'} ${x.valid!==false&&!x.duplicate?`<span class="saa-badge ${st==='aprovado'?'approved':'pending'}">${st==='aprovado'?'APROVADO':'PENDENTE'}</span>`:''}</div><div class="saa-meta">Campanha: ${esc(x.campaignId||'—')} · Divulgador: ${esc(x.promoterUid||'—')}<br>Valor teste: ${brl(x.reward)} · ${when(x.createdAt)}</div>${x.valid!==false&&!x.duplicate&&st!=='aprovado'?`<div class="saa-actions"><button class="saa-ok" data-approve-click="${esc(x.id)}">Aprovar este resultado</button></div>`:''}</div>`}).join(''):'<p>Nenhum clique registrado.</p>';xbox.onclick=async e=>{const b=e.target.closest('[data-approve-click]');if(!b)return;b.disabled=true;try{await setClickBalanceStatus(b.dataset.approveClick,'aprovado');openAdmin()}catch(err){alert('Não foi possível aprovar este resultado: '+err.message);b.disabled=false}}}catch(err){box.innerHTML=`<div class="saa-alert">Não foi possível carregar o painel administrativo. Verifique as regras do Firebase para as coleções do ShopAds.<br><br>${esc(err.message)}</div>`}}
function injectAdminButton(){if(!adminOk())return;const overlay=$('#shopAdsOverlay');if(!overlay||!overlay.classList.contains('open'))return;if($('#shopAdsAdminBtn',overlay))return;const results=overlay.querySelector('[data-results]');if(!results)return;const card=results.closest('.sa-card');if(!card)return;const b=document.createElement('button');b.id='shopAdsAdminBtn';b.type='button';b.className='sa-btn sa-admin-btn';b.textContent='🛡️ Admin ShopAds';b.onclick=openAdmin;card.appendChild(b)}
ensureStyles();window.openShopAdsAdmin=openAdmin;const obs=new MutationObserver(injectAdminButton);obs.observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});setInterval(injectAdminButton,1000);injectAdminButton();
})();