/* ShopAds — atribuição de ações ao divulgador. */
(function(){
'use strict';
if(window.__SHOPADS_TRACKER_LOADED)return;
window.__SHOPADS_TRACKER_LOADED=true;
const KEY='shopads_attribution_v2',TTL=30*24*60*60*1000;
const ACTION_LABELS={page_view:'Visita',download_chatshop:'Baixou ChatShop',signup_intent:'Clicou em cadastro',signup:'Cadastro concluído',catalog_created:'Criou catálogo',catalog_published:'Publicou catálogo',upgrade_intent:'Clicou em plano',checkout_started:'Iniciou pagamento',payment_approved:'Pagamento aprovado',purchase:'Compra'};
const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function dbRef(){try{return typeof db!=='undefined'&&db?db:null}catch(e){return null}}
function read(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(!x||!x.campaignId||Date.now()-Number(x.savedAt||0)>TTL)return null;return x}catch(e){return null}}
function save(x){try{localStorage.setItem(KEY,JSON.stringify({...x,savedAt:Date.now()}))}catch(e){}}
function capture(){const q=new URLSearchParams(location.search),campaignId=q.get('shopads_campaign')||'',promoterUid=q.get('shopads_promoter')||q.get('shopads_affiliate')||'',ownerUid=q.get('shopads_owner')||'',parentClickId=q.get('shopads_click')||'';if(!campaignId)return read();const x={campaignId,promoterUid,ownerUid,parentClickId,resultType:q.get('shopads_result')||''};save(x);return x}
async function track(action,metadata){const a=read()||capture();if(!a?.campaignId)return false;const d=dbRef();if(!d)return false;try{await d.collection('shopadsClicks').add({campaignId:a.campaignId,promoterUid:a.promoterUid||'',ownerUid:a.ownerUid||'',parentClickId:a.parentClickId||'',resultType:a.resultType||'',eventType:'action',action:String(action||'').slice(0,80),metadata:metadata&&typeof metadata==='object'?metadata:{},destination:location.href,valid:false,duplicate:false,reward:0,reason:'acao_atribuida',createdAt:new Date().toISOString(),userAgent:(navigator.userAgent||'').slice(0,300),referrer:(document.referrer||'').slice(0,500)});return true}catch(e){console.warn('ShopAds ação não registrada:',e);return false}}
window.ShopAdsTrack=track;
const attribution=capture();
function firstPageView(){if(!attribution)return;const k='shopads_page_'+(attribution.parentClickId||attribution.campaignId+'_'+attribution.promoterUid);try{if(sessionStorage.getItem(k))return;sessionStorage.setItem(k,'1')}catch(e){}let n=0,t=setInterval(()=>{n++;if(dbRef()){clearInterval(t);track('page_view')}else if(n>20)clearInterval(t)},250)}
function wireActions(){document.addEventListener('click',e=>{const el=e.target.closest('button,a');if(!el)return;const id=(el.id||'').toLowerCase(),txt=(el.textContent||'').toLowerCase();if(id==='chatshopdownloadbutton'||id==='chatshopinstallbutton'||txt.includes('baixar chatshop'))track('download_chatshop');else if(txt.includes('assinar')||txt.includes('plano básico')||txt.includes('plano profissional'))track('upgrade_intent');else if(txt.includes('criar conta')||txt.includes('cadastre')||txt.includes('cadastro'))track('signup_intent')},true)}
async function promoterName(uid,withdrawals){if(!uid)return'Direto / sem divulgador';const w=withdrawals.find(x=>x.promoterUid===uid&&x.promoterEmail);if(w?.promoterEmail)return w.promoterEmail;try{const s=await dbRef().collection('users').doc(uid).get();if(s.exists){const u=s.data()||{};return u.name||u.nome||u.displayName||u.email||uid}}catch(e){}return uid}
async function renderAdminAttribution(){const panel=document.getElementById('shopAdsAdminPanel'),body=panel?.querySelector('.saa-body');if(!panel||!body||!dbRef())return;let box=document.getElementById('saaAttribution');if(!box){box=document.createElement('section');box.id='saaAttribution';box.className='saa-card';box.innerHTML='<h2>🎯 Ações por divulgador</h2><div id="saaAttributionBody">Carregando...</div>';body.appendChild(box)}const out=box.querySelector('#saaAttributionBody');try{const [clickSnap,wSnap]=await Promise.all([dbRef().collection('shopadsClicks').get(),dbRef().collection('shopadsWithdrawals').get().catch(()=>({docs:[]}))]);const actions=clickSnap.docs.map(x=>({id:x.id,...x.data()})).filter(x=>x.eventType==='action'||x.action),withdrawals=wSnap.docs.map(x=>({id:x.id,...x.data()}));if(!actions.length){out.innerHTML='<p class="saa-meta">Ainda não há ações atribuídas.</p>';return}const groups={};for(const x of actions){const p=x.promoterUid||'direto',c=x.campaignId||'sem-campanha',key=p+'__'+c;if(!groups[key])groups[key]={promoterUid:p,campaignId:c,total:0,actions:{}};groups[key].total++;const a=x.action||'acao';groups[key].actions[a]=(groups[key].actions[a]||0)+1}const rows=Object.values(groups).sort((a,b)=>b.total-a.total);for(const g of rows)g.promoterName=await promoterName(g.promoterUid==='direto'?'':g.promoterUid,withdrawals);out.innerHTML=rows.map(g=>`<div class="saa-row"><div class="saa-title">${esc(g.promoterName)}</div><div class="saa-meta">Campanha: ${esc(g.campaignId)}<br>${Object.entries(g.actions).map(([a,n])=>`${esc(ACTION_LABELS[a]||a)}: <b>${n}</b>`).join(' · ')}</div></div>`).join('')}catch(e){out.innerHTML='<div class="saa-alert">Não foi possível carregar as ações: '+esc(e.message||e)+'</div>'}}
function watchAdmin(){let last=0;setInterval(()=>{const p=document.getElementById('shopAdsAdminPanel');if(!p||p.style.display==='none')return;const now=Date.now();if(now-last<2500&&document.getElementById('saaAttribution'))return;last=now;renderAdminAttribution()},1000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{wireActions();firstPageView();watchAdmin()},{once:true});else{wireActions();firstPageView();watchAdmin()}
})();
