/* ShopAds Wallet — privada e exclusiva para divulgadores cadastrados. */
(function(){
'use strict';const $=(s,r)=>(r||document).querySelector(s);
function dbRef(){try{return typeof db!=='undefined'&&db?db:null}catch(e){return null}}function uid(){try{return typeof myUid!=='undefined'&&myUid?myUid:(typeof currentUser!=='undefined'&&currentUser?.uid?currentUser.uid:'')}catch(e){return''}}function email(){try{return String((typeof currentUser!=='undefined'&&currentUser?.email)||'')}catch(e){return''}}function brl(v){return'R$ '+Number(v||0).toFixed(2).replace('.',',')}function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function hasProfile(){const d=dbRef();if(!d||!uid())return false;try{const s=await d.collection('divulgadores').doc(uid()).get();return s.exists&&s.data()?.profileCreated!==false}catch(e){return false}}
async function getClicks(){const d=dbRef();if(!d||!uid())return[];try{const s=await d.collection('shopadsClicks').where('promoterUid','==',uid()).get();return s.docs.map(x=>({id:x.id,...x.data()}))}catch(e){return[]}}
async function getCampaigns(){const d=dbRef();if(!d)return{};try{const s=await d.collection('shopadsCampaigns').get(),m={};s.docs.forEach(x=>m[x.id]={id:x.id,...x.data()});return m}catch(e){return{}}}
async function getWithdrawals(){const d=dbRef();if(!d||!uid())return[];try{const s=await d.collection('shopadsWithdrawals').where('promoterUid','==',uid()).get();return s.docs.map(x=>({id:x.id,...x.data()}))}catch(e){return[]}}
async function requestWithdrawal(amount){const d=dbRef();if(!d||!uid())throw new Error('Entre na sua conta.');if(!(await hasProfile()))throw new Error('Crie seu perfil de divulgador primeiro.');const active=(await getWithdrawals()).find(x=>x.status==='pendente');if(active)throw new Error('Você já possui um saque pendente.');await d.collection('shopadsWithdrawals').add({promoterUid:uid(),promoterEmail:email(),amount:Number(amount||0),status:'pendente',mode:'teste',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()})}
function styles(){if($('#shopAdsWalletStyles'))return;const s=document.createElement('style');s.id='shopAdsWalletStyles';s.textContent=`#shopAdsWallet{position:fixed;inset:0;z-index:10080;background:#f7f5ff;overflow:auto;display:none;font-family:Arial;color:#1f2937}#shopAdsWallet.open{display:block}.saw-top{background:linear-gradient(135deg,#166534,#16a34a);color:#fff;padding:18px}.saw-head,.saw-body{max-width:760px;margin:auto}.saw-head{display:flex;justify-content:space-between;align-items:center}.saw-close{border:0;background:#ffffff25;color:#fff;width:40px;height:40px;border-radius:50%;font-size:20px}.saw-body{padding:16px}.saw-card{background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:16px;margin-bottom:12px}.saw-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.saw-metric{padding:14px;border-radius:12px;background:#f9fafb;text-align:center;font-size:12px}.saw-metric b{display:block;font-size:22px}.saw-row{padding:12px 0;border-top:1px solid #eee;font-size:13px}.saw-btn{border:0;border-radius:10px;padding:12px;font-weight:900;background:#16a34a;color:#fff;width:100%}.saw-note{font-size:12px;color:#6b7280}@media(max-width:560px){.saw-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
async function openWallet(){if(!(await hasProfile())){alert('A Carteira ShopAds é exclusiva para divulgadores cadastrados. Crie seu perfil de divulgador primeiro.');window.openPromoterProfile?.();return}styles();let el=$('#shopAdsWallet');if(!el){el=document.createElement('div');el.id='shopAdsWallet';document.body.appendChild(el)}el.classList.add('open');el.innerHTML='<div class="saw-top"><div class="saw-head"><b>💰 Minha Carteira ShopAds</b><button class="saw-close">×</button></div></div><main class="saw-body"><section class="saw-card" id="sawContent">Carregando...</section></main>';$('.saw-close',el).onclick=()=>el.classList.remove('open');const box=$('#sawContent',el),[clicks,camps,withdrawals]=await Promise.all([getClicks(),getCampaigns(),getWithdrawals()]),valid=clicks.filter(x=>x.valid!==false&&!x.duplicate);let pending=0,approved=0;const rows=[];valid.forEach(x=>{const c=camps[x.campaignId]||{},value=Number(x.reward!=null?x.reward:c.reward||0),status=x.paymentStatus||x.balanceStatus||'pendente';status==='aprovado'?approved+=value:pending+=value;rows.push({x,c,value,status})});const withdrawn=withdrawals.filter(x=>x.status==='aprovado').reduce((s,x)=>s+Number(x.amount||0),0),requested=withdrawals.filter(x=>x.status==='pendente').reduce((s,x)=>s+Number(x.amount||0),0),available=Math.max(0,approved-withdrawn-requested);box.innerHTML=`<h2>Área financeira privada</h2><p class="saw-note">Somente você e o administrador têm acesso a estes valores.</p><div class="saw-grid"><div class="saw-metric">Pendente<b>${brl(pending)}</b></div><div class="saw-metric">Aprovado<b>${brl(approved)}</b></div><div class="saw-metric">Disponível<b>${brl(available)}</b></div></div><h3>Solicitar saque</h3><button class="saw-btn" id="sawWithdraw" ${available<=0||requested>0?'disabled':''}>${requested>0?'Saque aguardando análise':available>0?'Solicitar '+brl(available):'Sem saldo disponível'}</button><h3>Minhas ações e ganhos</h3>${rows.length?rows.slice().reverse().slice(0,100).map(r=>`<div class="saw-row"><b>${esc(r.c.title||r.x.campaignId||'Campanha')}</b><br>${brl(r.value)} · ${esc(r.status)}</div>`).join(''):'<p>Nenhuma ação registrada ainda.</p>'}`;const wb=$('#sawWithdraw',box);if(wb&&!wb.disabled)wb.onclick=async()=>{try{await requestWithdrawal(available);alert('Solicitação enviada.');openWallet()}catch(e){alert(e.message)}}}
async function syncButton(){const shop=$('#shopAdsBtn,[data-open-shopads]'),old=$('#shopAdsWalletBtn');if(!(await hasProfile())){old?.remove();return false}if(old)return true;if(!shop||!shop.parentElement)return false;const b=document.createElement('button');b.id='shopAdsWalletBtn';b.className=shop.className||'btn';b.textContent='💰 Carteira ShopAds';b.onclick=openWallet;shop.parentElement.insertBefore(b,shop.nextSibling);return true}
function install(){window.openShopAdsWallet=openWallet;syncButton();window.addEventListener('chatshop:promoter-profile-saved',syncButton);let n=0,t=setInterval(()=>{if(++n>40||$('#shopAdsWalletBtn'))clearInterval(t);else syncButton()},300)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();