import admin from 'firebase-admin';

const CHAMA_API_KEY='AIzaSyCcAVkmLUKPcEMZ5erDswbOQ8eO493pl2I';
const TARGET_PROJECT='chatshop-97ea3';

function json(res,status,data){res.status(status).setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(data))}
function getAdmin(){if(admin.apps.length)return admin.app();const raw=process.env.CHATSHOP_FIREBASE_SERVICE_ACCOUNT;if(!raw)throw new Error('CHATSHOP_FIREBASE_SERVICE_ACCOUNT ausente');const service=JSON.parse(raw);return admin.initializeApp({credential:admin.credential.cert(service),projectId:TARGET_PROJECT})}
async function verifyChama(idToken){const r=await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=${CHAMA_API_KEY}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idToken})});if(!r.ok)throw new Error('token_chama_invalido');const d=await r.json(),u=d?.users?.[0];if(!u?.localId||!u?.email)throw new Error('usuario_chama_invalido');return u}
export default async function handler(req,res){if(req.method!=='POST')return json(res,405,{ok:false,error:'method_not_allowed'});try{const token=String(req.body?.idToken||'');if(!token)return json(res,400,{ok:false,error:'token_ausente'});const chama=await verifyChama(token);const app=getAdmin(),auth=app.auth();let target;try{target=await auth.getUserByEmail(chama.email)}catch(e){if(e?.code!=='auth/user-not-found')throw e;target=await auth.createUser({email:chama.email,emailVerified:!!chama.emailVerified,displayName:chama.displayName||undefined,disabled:false})}const customToken=await auth.createCustomToken(target.uid,{sourcePlatform:'chama',chamaUid:chama.localId});return json(res,200,{ok:true,customToken,email:target.email||chama.email})}catch(e){console.error('auth-chama',e);const setup=String(e?.message||'').includes('CHATSHOP_FIREBASE_SERVICE_ACCOUNT');return json(res,setup?503:401,{ok:false,error:setup?'sso_not_configured':'sso_failed'})}}
